name = "news-dashboard-api"
main = "src/index.js"        # path to your Worker script
compatibility_date = "2024-08-25"

[[kv_namespaces]]
binding = "HEADLINES_STORE"
id      = "your-kv-namespace-id"

[[routes]]
pattern   = "yourdomain.com/api/*"
zone_name = "yourdomain.com"
