name: Build Sentiment Dashboard


on:
schedule:
- cron: '*/30 * * * *' # every 30 minutes
workflow_dispatch:


jobs:
build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.11'


- name: Install dependencies
run: |
python -m pip install --upgrade pip
pip install -r requirements.txt


- name: Run fetcher
run: python fetcher.py


- name: Commit and push changes
run: |
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
git add -A
git commit -m "Update sentiment data [skip ci]" || echo "No changes to commit"
git push
