name: Build Sentiment Dashboard

on:
  schedule:
    - cron: '*/30 * * * *'  # every 30 minutes
  workflow_dispatch:

# Ensure the workflow can push back to the repo
permissions:
  contents: write

concurrency:
  group: sentiment-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetcher
        run: python fetcher.py

      - name: Configure Git for push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

       - name: Commit and push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git pull --rebase || true
        git add -A
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update sentiment data [skip ci]"
          git push
        fi
